In [51]:
import pandas as pd

In [52]:
df = pd.read_excel('Фин данные ДАЙС.xlsx')

In [53]:
df.dtypes

gara_id                 object
bin                    float64
parent_id              float64
fin_id                  object
date_id                 object
date            datetime64[ns]
rank_num               float64
name                    object
value                  float64
update_date             object
category                object
subcategory             object
role                    object
company_name            object
dtype: object

In [54]:
print(df_grouped_pivot.columns)
df_grouped_pivot.columns = df_grouped_pivot.columns.str.strip()
available_columns = [col for col in essential_grouped_columns if col in df_grouped_pivot.columns]

# Create the filtered DataFrame
df_grouped_filtered = df_grouped_pivot[available_columns].copy()

Index(['bin', 'date_id', 'date', 'I. ДДС от операционной деятельности',
       'II. ДДС от инвестиционной деятельности',
       'III. ДДС от финансовой деятельности', 'Авансы выданные',
       'Авансы полученные', 'Авансы, полученные от покупателей',
       'Активы по отложенному подоходному налогу',
       ...
       'Текущие налоговые активы', 'Уставный капитал',
       'вознаграждения работникам', 'долгосрочные гарантийные обязательства',
       'инвестиции, учитываемые методом долевого участия',
       'краткосрочные финансовые активы, оцениваемые по амортизированной стоимости',
       'неоплаченный капитал', 'отложенные налоговые активы',
       'прочая краткосрочная задолженность',
       'прочие долгосрочные финансовые активы'],
      dtype='object', name='name', length=118)

In [55]:
df_pivot = df.pivot_table(
    values='value', 
    index=['bin', 'date_id', 'date', 'name'], 
    aggfunc='sum'
).reset_index()

# Поворот таблицы, чтобы столбец "name" стал заголовками столбцов
df_grouped_pivot = df_pivot.pivot(
    index=['bin', 'date_id', 'date'], 
    columns='name', 
    values='value'
).reset_index()

# Определение необходимых столбцов для анализа
essential_grouped_columns = [
    'bin', 'date_id', 'date', 'Итого краткосрочные активы', 'Итого краткосрочных обязательств',
    'Денежные средства', 'Краткосрочная дебиторская задолженность', 'Запасы', 'Себестоимость',
    'Доход от реализации', 'Итого активы', 'Итого капитал', 'Итого пассивы',
    'Краткосрочная кредиторская задолженность', 'Операционная прибыль',
    'Долгосрочные финансовые обязательства', 'Краткосрочные финансовые обязательства',
    'Итоговая прибыль (убыток)', 'Расходы на финансирование'
]

df_grouped_filtered = df_grouped_pivot[essential_grouped_columns].copy()

df_grouped_filtered['Коэффициент текущей ликвидности'] = (
    df_grouped_filtered['Итого краткосрочные активы'] / df_grouped_filtered['Итого краткосрочных обязательств']
)

df_grouped_filtered['Коэффициент быстрой ликвидности'] = (
    (df_grouped_filtered['Краткосрочная дебиторская задолженность'] + df_grouped_filtered['Денежные средства']) / 
    df_grouped_filtered['Итого краткосрочных обязательств']
)

df_grouped_filtered['Коэффициент абсолютной ликвидности'] = (
    df_grouped_filtered['Денежные средства'] / df_grouped_filtered['Итого краткосрочных обязательств']
)

df_grouped_filtered['Коэффициент оборачиваемости запасов'] = (
    df_grouped_filtered['Себестоимость'] / df_grouped_filtered['Запасы']
)

df_grouped_filtered['Коэффициент оборачиваемости активов'] = (
    df_grouped_filtered['Доход от реализации'] / df_grouped_filtered['Итого активы']
)

df_grouped_filtered['Коэффициент оборачиваемости кредиторской задолженности'] = (
    df_grouped_filtered['Себестоимость'] / df_grouped_filtered['Краткосрочная кредиторская задолженность']
)

df_grouped_filtered['ROA'] = (
    df_grouped_filtered['Итоговая прибыль (убыток)'] / df_grouped_filtered['Итого активы']
)

df_grouped_filtered['ROE'] = (
    df_grouped_filtered['Итоговая прибыль (убыток)'] / df_grouped_filtered['Итого капитал']
)

df_grouped_filtered['Коэффициент чистой прибыли'] = (
    df_grouped_filtered['Итоговая прибыль (убыток)'] / df_grouped_filtered['Доход от реализации']
)

df_grouped_filtered['Коэффициент финансового левериджа'] = (
    df_grouped_filtered['Итого пассивы'] / df_grouped_filtered['Итого капитал']
)

df_grouped_filtered['Коэффициент финансовой независимости'] = (
    df_grouped_filtered['Итого капитал'] / df_grouped_filtered['Итого активы']
)

df_grouped_filtered['Коэффициент долговой нагрузки'] = (
    df_grouped_filtered['Итого пассивы'] / df_grouped_filtered['Итого активы']
)

df_grouped_filtered['Коэффициент долг на капитал'] = (
    (df_grouped_filtered['Краткосрочные финансовые обязательства'] + 
     df_grouped_filtered['Долгосрочные финансовые обязательства']) / 
    df_grouped_filtered['Итого капитал']
)

df_grouped_filtered['Коэффициент покрытия процентов'] = (
    df_grouped_filtered['Операционная прибыль'] / df_grouped_filtered['Расходы на финансирование']
)

df_grouped_filtered['Покрытие долга'] = (
    df_grouped_filtered['Операционная прибыль'] / 
    (df_grouped_filtered['Краткосрочные финансовые обязательства'] + df_grouped_filtered['Долгосрочные финансовые обязательства'])
)

df_final = pd.merge(
    df, df_grouped_filtered, 
    how='left', 
    left_on=['bin', 'date_id', 'date'], 
    right_on=['bin', 'date_id', 'date']
)

df_final

,gara_id,bin,parent_id,fin_id,date_id,date,rank_num,name,value,update_date,...,Коэффициент оборачиваемости кредиторской задолженности,ROA,ROE,Коэффициент чистой прибыли,Коэффициент финансового левериджа,Коэффициент финансовой независимости,Коэффициент долговой нагрузки,Коэффициент долг на капитал,Коэффициент покрытия процентов,Покрытие долга
0,1124311,1.708400e+11,2.0,2001-01-01 00:00:00,year-1,2022-12-31,1124311.0,Краткосрочная дебиторская задолженность,1361507.0,2024-03-27 06:37:34.465619,...,0.035186,0.025911,0.106907,0.363323,4.125889,0.242372,1.00000,0.000000,inf,inf
1,1124311,1.708400e+11,2.0,2001-01-01 00:00:00,year-2,2021-12-31,1124311.0,Краткосрочная дебиторская задолженность,1400959.0,2024-03-27 06:37:34.465619,...,0.176416,0.083026,0.401817,0.324737,4.839682,0.206625,1.00000,0.000000,inf,inf
2,1124311,1.708400e+11,2.0,2001-01-01 00:00:00,year_current,2023-12-31,1124311.0,Краткосрочная дебиторская задолженность,6100.0,2024-03-27 06:37:34.465619,...,65.146437,-0.033176,-0.218869,-1.112687,6.597274,0.151578,1.00000,5.479264,-inf,-0.039945
3,1124311,1.708400e+11,3.0,2001-01-01 00:00:00,year-1,2022-12-31,1124311.0,Запасы,795139.0,2024-03-27 06:37:34.465619,...,0.035186,0.025911,0.106907,0.363323,4.125889,0.242372,1.00000,0.000000,inf,inf
4,1124311,1.708400e+11,3.0,2001-01-01 00:00:00,year-2,2021-12-31,1124311.0,Запасы,898369.0,2024-03-27 06:37:34.465619,...,0.176416,0.083026,0.401817,0.324737,4.839682,0.206625,1.00000,0.000000,inf,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46547,1397186,1.502400e+11,24.0,1.4.1.4,year_current,2024-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),36764.0,2024-09-27 09:00:00.883837,...,NaN,0.166824,0.194002,0.998705,1.162912,0.859911,1.00000,0.015834,inf,12.252353
46548,1397186,1.502400e+11,24.0,1.4.1.4,year-1,2023-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),-2306.0,2024-09-11 18:00:00.644409,...,NaN,0.432207,0.439979,0.939496,1.017981,0.982337,1.00000,0.000000,inf,inf
46549,1397186,1.502400e+11,24.0,1.4.1.4,year-1,2023-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),-2306.0,2024-09-27 09:00:00.883837,...,NaN,0.432207,0.439979,0.939496,1.017981,0.982337,1.00000,0.000000,inf,inf
46550,1397186,1.502400e+11,24.0,1.4.1.4,year-2,2022-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),-322.0,2024-09-11 18:00:00.644409,...,NaN,0.571359,0.582654,0.957445,1.019748,0.980615,0.99998,0.000000,inf,inf
46551,1397186,1.502400e+11,24.0,1.4.1.4,year-2,2022-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),-322.0,2024-09-27 09:00:00.883837,...,NaN,0.571359,0.582654,0.957445,1.019748,0.980615,0.99998,0.000000,inf,inf

In [56]:
df_final.to_excel('фин данные с кофф.xlsx')

In [57]:
df1 = pd.read_excel('243 проекты.xlsx')

In [58]:
df_filtered = df1[df1['type'] != 'расторжение']

In [59]:
df_filtered.rename(columns = {'builder_id': 'bin', 'start_date':'date'}, inplace = True)
df_final.columns

C:\Users\Norynbayev\AppData\Local\Temp\ipykernel_9736\2713403064.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered.rename(columns = {'builder_id': 'bin', 'start_date':'date'}, inplace = True)

Index(['gara_id', 'bin', 'parent_id', 'fin_id', 'date_id', 'date', 'rank_num',
       'name', 'value', 'update_date', 'category', 'subcategory', 'role',
       'company_name', 'Итого краткосрочные активы',
       'Итого краткосрочных обязательств', 'Денежные средства',
       'Краткосрочная дебиторская задолженность', 'Запасы', 'Себестоимость',
       'Доход от реализации', 'Итого активы', 'Итого капитал', 'Итого пассивы',
       'Краткосрочная кредиторская задолженность', 'Операционная прибыль',
       'Долгосрочные финансовые обязательства',
       'Краткосрочные финансовые обязательства', 'Итоговая прибыль (убыток)',
       'Расходы на финансирование', 'Коэффициент текущей ликвидности',
       'Коэффициент быстрой ликвидности', 'Коэффициент абсолютной ликвидности',
       'Коэффициент оборачиваемости запасов',
       'Коэффициент оборачиваемости активов',
       'Коэффициент оборачиваемости кредиторской задолженности', 'ROA', 'ROE',
       'Коэффициент чистой прибыли', 'Коэффициент финансового левериджа',
       'Коэффициент финансовой независимости', 'Коэффициент долговой нагрузки',
       'Коэффициент долг на капитал', 'Коэффициент покрытия процентов',
       'Покрытие долга'],
      dtype='object')

In [60]:
df_final['date'] = pd.to_datetime(df_final['date'], dayfirst=True, errors='coerce')

df_final['date'] = df_final['date'].apply(
    lambda x: pd.Timestamp(year=x.year - 1, month=12, day=31) if pd.notnull(x) else pd.NaT
)

df_final

,gara_id,bin,parent_id,fin_id,date_id,date,rank_num,name,value,update_date,...,Коэффициент оборачиваемости кредиторской задолженности,ROA,ROE,Коэффициент чистой прибыли,Коэффициент финансового левериджа,Коэффициент финансовой независимости,Коэффициент долговой нагрузки,Коэффициент долг на капитал,Коэффициент покрытия процентов,Покрытие долга
0,1124311,1.708400e+11,2.0,2001-01-01 00:00:00,year-1,2021-12-31,1124311.0,Краткосрочная дебиторская задолженность,1361507.0,2024-03-27 06:37:34.465619,...,0.035186,0.025911,0.106907,0.363323,4.125889,0.242372,1.00000,0.000000,inf,inf
1,1124311,1.708400e+11,2.0,2001-01-01 00:00:00,year-2,2020-12-31,1124311.0,Краткосрочная дебиторская задолженность,1400959.0,2024-03-27 06:37:34.465619,...,0.176416,0.083026,0.401817,0.324737,4.839682,0.206625,1.00000,0.000000,inf,inf
2,1124311,1.708400e+11,2.0,2001-01-01 00:00:00,year_current,2022-12-31,1124311.0,Краткосрочная дебиторская задолженность,6100.0,2024-03-27 06:37:34.465619,...,65.146437,-0.033176,-0.218869,-1.112687,6.597274,0.151578,1.00000,5.479264,-inf,-0.039945
3,1124311,1.708400e+11,3.0,2001-01-01 00:00:00,year-1,2021-12-31,1124311.0,Запасы,795139.0,2024-03-27 06:37:34.465619,...,0.035186,0.025911,0.106907,0.363323,4.125889,0.242372,1.00000,0.000000,inf,inf
4,1124311,1.708400e+11,3.0,2001-01-01 00:00:00,year-2,2020-12-31,1124311.0,Запасы,898369.0,2024-03-27 06:37:34.465619,...,0.176416,0.083026,0.401817,0.324737,4.839682,0.206625,1.00000,0.000000,inf,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46547,1397186,1.502400e+11,24.0,1.4.1.4,year_current,2023-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),36764.0,2024-09-27 09:00:00.883837,...,NaN,0.166824,0.194002,0.998705,1.162912,0.859911,1.00000,0.015834,inf,12.252353
46548,1397186,1.502400e+11,24.0,1.4.1.4,year-1,2022-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),-2306.0,2024-09-11 18:00:00.644409,...,NaN,0.432207,0.439979,0.939496,1.017981,0.982337,1.00000,0.000000,inf,inf
46549,1397186,1.502400e+11,24.0,1.4.1.4,year-1,2022-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),-2306.0,2024-09-27 09:00:00.883837,...,NaN,0.432207,0.439979,0.939496,1.017981,0.982337,1.00000,0.000000,inf,inf
46550,1397186,1.502400e+11,24.0,1.4.1.4,year-2,2021-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),-322.0,2024-09-11 18:00:00.644409,...,NaN,0.571359,0.582654,0.957445,1.019748,0.980615,0.99998,0.000000,inf,inf
46551,1397186,1.502400e+11,24.0,1.4.1.4,year-2,2021-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),-322.0,2024-09-27 09:00:00.883837,...,NaN,0.571359,0.582654,0.957445,1.019748,0.980615,0.99998,0.000000,inf,inf

In [61]:
df = pd.merge(df_final, df_filtered, on=['bin', 'date'], how='left')

In [62]:
df.columns

Index(['gara_id_x', 'bin', 'parent_id', 'fin_id', 'date_id', 'date',
       'rank_num', 'name_x', 'value', 'update_date_x', 'category',
       'subcategory', 'role', 'company_name', 'Итого краткосрочные активы',
       'Итого краткосрочных обязательств', 'Денежные средства',
       'Краткосрочная дебиторская задолженность', 'Запасы', 'Себестоимость',
       'Доход от реализации', 'Итого активы', 'Итого капитал', 'Итого пассивы',
       'Краткосрочная кредиторская задолженность', 'Операционная прибыль',
       'Долгосрочные финансовые обязательства',
       'Краткосрочные финансовые обязательства', 'Итоговая прибыль (убыток)',
       'Расходы на финансирование', 'Коэффициент текущей ликвидности',
       'Коэффициент быстрой ликвидности', 'Коэффициент абсолютной ликвидности',
       'Коэффициент оборачиваемости запасов',
       'Коэффициент оборачиваемости активов',
       'Коэффициент оборачиваемости кредиторской задолженности', 'ROA', 'ROE',
       'Коэффициент чистой прибыли', 'Коэффициент финансового левериджа',
       'Коэффициент финансовой независимости', 'Коэффициент долговой нагрузки',
       'Коэффициент долг на капитал', 'Коэффициент покрытия процентов',
       'Покрытие долга', 'gara_id_y', 'application_name', 'author_id',
       'contractor_id', 'designer_id', 'engine_id', 'manager_id', 'status',
       'decision_date', 'region_name', 'city_id', 'type', 'turn', 'network',
       'period_month', 'end_date', 'class', 'flat_area', 'build_qty',
       'build_floor', 'build_area', 'com_area', 'park_area', 'flat_qty',
       'com_qty', 'park_qty', 'flat_onerm', 'flat_tworm', 'flat_threerm',
       'flat_fourrm', 'cost_plan', 'flat_msprice', 'build_mscost',
       'flat_mscost', 'com_msprice', 'park_price', 'self_cost', 'unfin_cost',
       'share_cost', 'warr_cost', 'comm_cost', 'cost_official', 'flat_inner',
       'flat_height', 'dpg_date', 'dpg_num', 'dpg_add_num', 'dpg_num_text',
       'prolongation', 'update_date_y', 'state_id', 'annul_date', 'name_y'],
      dtype='object')

In [63]:
df

,gara_id_x,bin,parent_id,fin_id,date_id,date,rank_num,name_x,value,update_date_x,...,flat_height,dpg_date,dpg_num,dpg_add_num,dpg_num_text,prolongation,update_date_y,state_id,annul_date,name_y
0,1124311,1.708400e+11,2.0,2001-01-01 00:00:00,year-1,2021-12-31,1124311.0,Краткосрочная дебиторская задолженность,1361507.0,2024-03-27 06:37:34.465619,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
1,1124311,1.708400e+11,2.0,2001-01-01 00:00:00,year-2,2020-12-31,1124311.0,Краткосрочная дебиторская задолженность,1400959.0,2024-03-27 06:37:34.465619,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
2,1124311,1.708400e+11,2.0,2001-01-01 00:00:00,year_current,2022-12-31,1124311.0,Краткосрочная дебиторская задолженность,6100.0,2024-03-27 06:37:34.465619,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
3,1124311,1.708400e+11,3.0,2001-01-01 00:00:00,year-1,2021-12-31,1124311.0,Запасы,795139.0,2024-03-27 06:37:34.465619,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4,1124311,1.708400e+11,3.0,2001-01-01 00:00:00,year-2,2020-12-31,1124311.0,Запасы,898369.0,2024-03-27 06:37:34.465619,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46547,1397186,1.502400e+11,24.0,1.4.1.4,year_current,2023-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),36764.0,2024-09-27 09:00:00.883837,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
46548,1397186,1.502400e+11,24.0,1.4.1.4,year-1,2022-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),-2306.0,2024-09-11 18:00:00.644409,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
46549,1397186,1.502400e+11,24.0,1.4.1.4,year-1,2022-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),-2306.0,2024-09-27 09:00:00.883837,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
46550,1397186,1.502400e+11,24.0,1.4.1.4,year-2,2021-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),-322.0,2024-09-11 18:00:00.644409,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
46551,1397186,1.502400e+11,24.0,1.4.1.4,year-2,2021-12-31,1397186.0,Итого (увеличение + / - уменьшение ДС),-322.0,2024-09-27 09:00:00.883837,...,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN

In [64]:
df.to_excel('Final_data.xlsx')